[book]
authors = ["Cædrik Labrecque"]
language = "fr"
src = "src"
title = "BCTC"

[output.html]
additional-css = ["custom.css"]
default-theme = "light"

[preprocessor.yapp]

[preprocessor.image-size]
command = "mdbook-image-size"

[preprocessor.alerts]
